formats:

- name: small
  format: '%<cqts> %<crc> %<ttms>'

- name: exp
  format: '%<cqts> %<cquc> %<crc> %<chm> %<cwr> %<psql> %<ttms>'

logs:
- mode: ascii
  format: small
  filename: small
  rolling_enabled: time
  rolling_interval_sec: 3600
  rolling_offset_hr: 0
